server:
  port: ${PORT}

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service-route
          uri: ${AUTH_SERVICE_ROUTE}
          predicates:
            - Path=/api/auth/**
        - id: user-service-route
          uri: ${USER_SERVICE_ROUTE}
          predicates:
            - Path=/api/users/**
        - id: parcel-service-route
          uri: ${PARCEL_SERVICE_ROUTE}
          predicates:
            - Path=/api/parcels/**
        - id: parcel-service-admin-route
          uri: ${PARCEL_SERVICE_ROUTE}
          predicates:
            - Path=/api/admin/parcels/**
    globalcors:
      add-to-chain: true
      cors-configurations:
        '[/**]':
          allowedOrigins: "*"
          allowedMethods:
            - GET
            - POST
            - PATCH
            - PUT
            - DELETE
            - OPTIONS
          allowedHeaders: "*"

springdoc:
  server:
#    url: http://localhost:8080
    url: ${BASE_URL}
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    urls:
      - name: "Parcel Service"
        url: /api/parcels/v3/api-docs
      - name: "User Service"
        url: /api/users/v3/api-docs
      - name: "Auth Service"
        url: /api/auth/v3/api-docs