ALTER TABLE additional_services ADD COLUMN version BIGINT DEFAULT 0 NOT NULL;

ALTER TABLE parcel_types ADD COLUMN version BIGINT DEFAULT 0 NOT NULL;

ALTER TABLE parcels ADD COLUMN version BIGINT DEFAULT 0 NOT NULL;

